const products = [
    {
        Product_image: ["https://m.media-amazon.com/images/I/71d5ISfq98L._SX522_.jpg"],
        Name: "Hape Wooden Dollhouse Furniture Set – Kitchen Playset for Kids",
        Brand_name: "Visit the Hape Store",
        Price: "₹799",
        Rating: 4.8,
        Rating_count: "56",
        MRP: "₹1299",
        Discount: "-38%",
        colour: "Multicolor",
        day: "Wednesday, 8 January",
        time: "5 hrs 30 mins",
        delivery: "Delivering to Mumbai 400001 - Update location",
        productBrought: "1.2K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Up to ₹1,500.00 discount on select...",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Get GST invoice and save up to 18% on...",
            },
        ],
        About_this_item: [
            "Includes furniture pieces for kitchen: Refrigerator, Oven, Sink, Table, etc.",
            "Color: Multicolor | Material: Wood",
            "Special Feature: Eco-friendly, non-toxic paints, and durable wood",
            "Age Range Description: 3 years and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/71j9OMi5joL._SX522_.jpg"],
        Name: "LEGO City Police Station Set",
        Brand_name: "Visit the LEGO Store",
        Price: "₹3,999",
        Rating: 4.7,
        Rating_count: "102",
        MRP: "₹4,999",
        Discount: "-20%",
        colour: "Multicolor",
        day: "Thursday, 9 January",
        time: "2 hrs 15 mins",
        delivery: "Delivering to Delhi 110001 - Update location",
        productBrought: "2.5K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Flat ₹500 discount on HDFC credit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Up to 15% off with selected bank partners",
            },
        ],
        About_this_item: [
            "Includes 6 mini-figures: police officers, criminals, and accessories",
            "Color: Multicolor | Material: Plastic",
            "Special Feature: Building set with detailed police station",
            "Age Range Description: 5 years and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/81vFO5CZqkL._SX522_.jpg"],
        Name: "Barbie Dreamhouse Dollhouse with Pool and Furniture",
        Brand_name: "Visit the Barbie Store",
        Price: "₹4,499",
        Rating: 4.8,
        Rating_count: "325",
        MRP: "₹6,999",
        Discount: "-36%",
        colour: "Pink",
        day: "Monday, 6 January",
        time: "10 hrs 5 mins",
        delivery: "Delivering to Bangalore 560001 - Update location",
        productBrought: "1.1K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "10% off on ICICI credit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Get extra 5% off on your next order",
            },
        ],
        About_this_item: [
            "Includes house, pool, furniture, and accessories",
            "Color: Pink | Material: Plastic",
            "Special Feature: Lights up with working lights",
            "Age Range Description: 3 years and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/71Fz8WqdMzL._SX522_.jpg"],
        Name: "Play-Doh Ultimate Creativity Set",
        Brand_name: "Visit the Play-Doh Store",
        Price: "₹1,199",
        Rating: 4.7,
        Rating_count: "123",
        MRP: "₹1,699",
        Discount: "-29%",
        colour: "Multicolor",
        day: "Tuesday, 7 January",
        time: "6 hrs 45 mins",
        delivery: "Delivering to Kolkata 700001 - Update location",
        productBrought: "900+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Get 10% cashback on Axis Bank credit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Flat 15% off on select items",
            },
        ],
        About_this_item: [
            "Includes 40 tools and 8 cans of Play-Doh",
            "Color: Multicolor | Material: Dough",
            "Special Feature: Allows for creative expression, non-toxic material",
            "Age Range Description: 3 years and up",
            "Assembly Required: No",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/71pNSDHzNeL._SX522_.jpg"],
        Name: "Fisher-Price Laugh & Learn Smart Stages Chair",
        Brand_name: "Visit the Fisher-Price Store",
        Price: "₹2,299",
        Rating: 4.8,
        Rating_count: "95",
        MRP: "₹3,499",
        Discount: "-34%",
        colour: "Blue",
        day: "Saturday, 4 January",
        time: "1 hr 30 mins",
        delivery: "Delivering to Hyderabad 500001 - Update location",
        productBrought: "1K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Get up to ₹1,000 off with select credit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Free delivery on select items",
            },
        ],
        About_this_item: [
            "Interactive chair that teaches shapes, colors, numbers, and more",
            "Color: Blue | Material: Plastic",
            "Special Feature: 3 Smart Stages of play",
            "Age Range Description: 6 months and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/81RH0LVpfdL._SX522_.jpg"],
        Name: "Hot Wheels Track Set",
        Brand_name: "Visit the Hot Wheels Store",
        Price: "₹1,299",
        Rating: 4.9,
        Rating_count: "150",
        MRP: "₹1,799",
        Discount: "-28%",
        colour: "Red",
        day: "Wednesday, 8 January",
        time: "4 hrs 20 mins",
        delivery: "Delivering to Chennai 600001 - Update location",
        productBrought: "3K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Get 10% cashback on HDFC debit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Buy 2 get 1 free on select items",
            },
        ],
        About_this_item: [
            "Includes race cars and track-building pieces",
            "Color: Red | Material: Plastic",
            "Special Feature: Speed track and loop-the-loop",
            "Age Range Description: 4 years and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/71q0jEZ1PWL._SX522_.jpg"],
        Name: "VTech Sit-to-Stand Learning Walker",
        Brand_name: "Visit the VTech Store",
        Price: "₹2,099",
        Rating: 4.7,
        Rating_count: "210",
        MRP: "₹3,299",
        Discount: "-36%",
        colour: "Green",
        day: "Tuesday, 7 January",
        time: "12 hrs 50 mins",
        delivery: "Delivering to Jaipur 302001 - Update location",
        productBrought: "1.5K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Get 15% cashback on ICICI Bank cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Up to 10% off with select partners",
            },
        ],
        About_this_item: [
            "Features light-up buttons, music, and educational activities",
            "Color: Green | Material: Plastic",
            "Special Feature: Interactive learning through play",
            "Age Range Description: 9 months and up",
            "Assembly Required: Yes",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/81lTFiilzYL._SX522_.jpg"],
        Name: "Disney Princess Cinderella Doll with Accessories",
        Brand_name: "Visit the Disney Store",
        Price: "₹1,499",
        Rating: 4.8,
        Rating_count: "220",
        MRP: "₹2,299",
        Discount: "-34%",
        colour: "Blue",
        day: "Monday, 6 January",
        time: "2 hrs 50 mins",
        delivery: "Delivering to Noida 201301 - Update location",
        productBrought: "1K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Up to ₹500 discount on SBI cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Get 10% off on next order",
            },
        ],
        About_this_item: [
            "Includes Cinderella doll and accessories",
            "Color: Blue | Material: Plastic",
            "Special Feature: Movable arms and legs",
            "Age Range Description: 3 years and up",
            "Assembly Required: No",
        ],
    },
    {
        Product_image: ["https://m.media-amazon.com/images/I/71HdbvP72yL._SX522_.jpg"],
        Name: "Crayola Washable Markers – 10 Colors Set",
        Brand_name: "Visit the Crayola Store",
        Price: "₹399",
        Rating: 4.6,
        Rating_count: "512",
        MRP: "₹599",
        Discount: "-33%",
        colour: "Multicolor",
        day: "Wednesday, 8 January",
        time: "3 hrs 25 mins",
        delivery: "Delivering to Ahmedabad 380001 - Update location",
        productBrought: "3.5K+ bought",
        name_mrp:"M.R.P:",
        Offers: [
            {
                Offer_name: "Bank Offer",
                Offer: "Flat ₹200 off with HDFC credit cards",
            },
            {
                Offer_name: "Partner Offer",
                Offer: "Get 5% cashback on select purchases",
            },
        ],
        About_this_item: [
            "Pack of 10 washable markers in vibrant colors",
            "Color: Multicolor | Material: Ink",
            "Special Feature: Washable and non-toxic ink",
            "Age Range Description: 3 years and up",
            "Assembly Required: No",
        ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/81lFzR-7VLL._SX522_.jpg",
            ],
            Name: "Disney Princess Ariel Doll with Accessories",
            Brand_name: "Visit the Disney Store",
            Price: "₹999",
            Rating: 4.8,
            Rating_count: "120",
            MRP: "₹1,499",
            Discount: "-33%",
            colour: "Red",
            day: "Wednesday, 8 January",
            time: "2 hrs 45 mins",
            delivery: "Delivering to Bangalore 560001 - Update location",
            productBrought: "1.5K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "Flat ₹300 off with SBI cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "10% off on next purchase",
                },
            ],
            About_this_item: [
                "Includes Ariel doll with detachable accessories",
                "Color: Red | Material: Plastic",
                "Special Feature: Movable arms and legs",
                "Age Range Description: 3 years and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/91Fc1au2J1L._SX522_.jpg",
            ],
            Name: "LEGO Classic Bricks and Eyes Set",
            Brand_name: "Visit the LEGO Store",
            Price: "₹1,599",
            Rating: 4.7,
            Rating_count: "245",
            MRP: "₹2,399",
            Discount: "-33%",
            colour: "Multicolor",
            day: "Monday, 6 January",
            time: "1 hr 50 mins",
            delivery: "Delivering to Chennai 600001 - Update location",
            productBrought: "2K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "Get 10% cashback on ICICI credit cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Flat ₹500 off on select items",
                },
            ],
            About_this_item: [
                "Includes a variety of bricks with eyes for creative builds",
                "Color: Multicolor | Material: Plastic",
                "Special Feature: Encourages creative thinking and imagination",
                "Age Range Description: 4 years and up",
                "Assembly Required: Yes",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/81dV4LxjsGL._SX522_.jpg",
            ],
            Name: "Hot Wheels 9-Pack Vehicle Set",
            Brand_name: "Visit the Hot Wheels Store",
            Price: "₹899",
            Rating: 4.9,
            Rating_count: "310",
            MRP: "₹1,499",
            Discount: "-40%",
            colour: "Multicolor",
            day: "Tuesday, 7 January",
            time: "3 hrs 30 mins",
            delivery: "Delivering to Delhi 110001 - Update location",
            productBrought: "3K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "Up to ₹500 off on HDFC credit cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Buy 1, get 1 at 50% off on select items",
                },
            ],
            About_this_item: [
                "Includes 9 cars from the Hot Wheels series",
                "Color: Multicolor | Material: Die-cast metal",
                "Special Feature: Realistic design with working wheels",
                "Age Range Description: 3 years and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/81z8mFY-aDL._SX522_.jpg",
            ],
            Name: "Fisher-Price Little People Animal Friends Playset",
            Brand_name: "Visit the Fisher-Price Store",
            Price: "₹1,199",
            Rating: 4.8,
            Rating_count: "88",
            MRP: "₹1,699",
            Discount: "-29%",
            colour: "Multicolor",
            day: "Thursday, 9 January",
            time: "4 hrs 15 mins",
            delivery: "Delivering to Pune 411001 - Update location",
            productBrought: "700+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "5% off on Axis Bank cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Get an extra 10% off on selected items",
                },
            ],
            About_this_item: [
                "Includes animal figures and interactive features",
                "Color: Multicolor | Material: Plastic",
                "Special Feature: Animal sounds and songs",
                "Age Range Description: 1 year and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/91dzn2DbxxL._SX522_.jpg",
            ],
            Name: "Barbie Fashionista Doll – Extra Special Edition",
            Brand_name: "Visit the Barbie Store",
            Price: "₹1,399",
            Rating: 4.7,
            Rating_count: "195",
            MRP: "₹1,899",
            Discount: "-26%",
            colour: "Pink",
            day: "Friday, 10 January",
            time: "5 hrs 50 mins",
            delivery: "Delivering to Mumbai 400001 - Update location",
            productBrought: "2K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "Up to ₹500 off with Kotak Mahindra cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "5% cashback on selected orders",
                },
            ],
            About_this_item: [
                "Includes Barbie doll with fashionable attire",
                "Color: Pink | Material: Plastic",
                "Special Feature: Fully poseable arms and legs",
                "Age Range Description: 3 years and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/91LUhJlybWL._SX522_.jpg",
            ],
            Name: "VTech KidiZoom Smartwatch DX2",
            Brand_name: "Visit the VTech Store",
            Price: "₹4,499",
            Rating: 4.6,
            Rating_count: "75",
            MRP: "₹5,999",
            Discount: "-25%",
            colour: "Blue",
            day: "Saturday, 11 January",
            time: "3 hrs 25 mins",
            delivery: "Delivering to Kolkata 700001 - Update location",
            productBrought: "950+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "₹500 cashback with ICICI credit card",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Free delivery on orders above ₹999",
                },
            ],
            About_this_item: [
                "Smartwatch with games, camera, and video recorder",
                "Color: Blue | Material: Plastic",
                "Special Feature: Waterproof, age-appropriate learning tools",
                "Age Range Description: 4 years and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/81Bd0LMoEwL._SX522_.jpg",
            ],
            Name: "Play-Doh Kitchen Creations Ultimate Dinner Set",
            Brand_name: "Visit the Play-Doh Store",
            Price: "₹1,499",
            Rating: 4.8,
            Rating_count: "200",
            MRP: "₹2,099",
            Discount: "-28%",
            colour: "Multicolor",
            day: "Sunday, 12 January",
            time: "6 hrs 40 mins",
            delivery: "Delivering to Hyderabad 500001 - Update location",
            productBrought: "1.3K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "10% off on SBI credit cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Buy 2 and get 20% off on selected products",
                },
            ],
            About_this_item: [
                "Includes molds and kitchen-themed accessories",
                "Color: Multicolor | Material: Dough and plastic",
                "Special Feature: Non-toxic and washable",
                "Age Range Description: 3 years and up",
                "Assembly Required: No",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/91rgCoalN2L._SX522_.jpg",
            ],
            Name: "LEGO Friends Heartlake City Amusement Pier",
            Brand_name: "Visit the LEGO Store",
            Price: "₹3,799",
            Rating: 4.9,
            Rating_count: "310",
            MRP: "₹4,999",
            Discount: "-24%",
            colour: "Multicolor",
            day: "Monday, 13 January",
            time: "2 hrs 30 mins",
            delivery: "Delivering to Delhi 110001 - Update location",
            productBrought: "2.2K+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "₹300 cashback on Axis Bank cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "Free return and exchange policy",
                },
            ],
            About_this_item: [
                "Includes Ferris wheel, roller coaster, and ride elements",
                "Color: Multicolor | Material: Plastic",
                "Special Feature: Realistic theme park design",
                "Age Range Description: 6 years and up",
                "Assembly Required: Yes",
            ],
    },
    {
            Product_image: [
                "https://m.media-amazon.com/images/I/81q2UOe1BqL._SX522_.jpg",
            ],
            Name: "VTech Touch and Learn Activity Desk",
            Brand_name: "Visit the VTech Store",
            Price: "₹3,499",
            Rating: 4.7,
            Rating_count: "325",
            MRP: "₹4,999",
            Discount: "-30%",
            colour: "Multicolor",
            day: "Tuesday, 14 January",
            time: "3 hrs 50 mins",
            delivery: "Delivering to Bangalore 560001 - Update location",
            productBrought: "900+ bought",
            name_mrp:"M.R.P:",
            Offers: [
                {
                    Offer_name: "Bank Offer",
                    Offer: "Flat ₹400 off on HDFC cards",
                },
                {
                    Offer_name: "Partner Offer",
                    Offer: "10% discount on first order",
                },
            ],
            About_this_item: [
                "Interactive learning desk with sounds and lights",
                "Color: Multicolor | Material: Plastic",
                "Special Feature: Touchscreen, learning activities",
                "Age Range Description: 2 years and up",
                "Assembly Required: Yes",
            ],
    }
];
    

